apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myexample-role
  namespace: mynamespacce
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
